# This should work for every systemd powered system
- mtu: "1492"

- set_hostname:
  - exec_in: echo $$hostname > /etc/hostname

- enable_network:
  - exec_in: chkconfig network on

- set_host:
  - write_in:
    - /etc/hosts
    - |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 $$hostname
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 $$hostname
